<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adult</name>
   <tag></tag>
   <elementGuidId>45614df2-6c2d-4f2e-9f18-52d72095b753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='passenger-action-box fadeInDown-enter-done']//div[1]//div[2]//div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.tix.tix-plus.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tix tix-plus icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formhome&quot;)/div[@class=&quot;flight-content&quot;]/div[@class=&quot;home-train&quot;]/div[@class=&quot;train-form z-index-999&quot;]/div[@class=&quot;form-style&quot;]/div[@class=&quot;part-component part-passenger&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;passenger-and-class-area&quot;]/div[@class=&quot;passenger-action-box fadeInDown-enter-done&quot;]/div[@class=&quot;passenger-box&quot;]/div[@class=&quot;passenger-list-box&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;part&quot;]/button[1]/i[@class=&quot;tix tix-plus icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formhome']/div/div/div/div[3]/div[6]/div[2]/div/div/div[2]/div/div[2]/div[3]/button/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/i</value>
   </webElementXpaths>
</WebElementEntity>
