<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_BCA Virtual Account_tix-ui-fadeIn</name>
   <tag></tag>
   <elementGuidId>7d37b5e1-bfdb-42f7-87c5-1dad41b0ff3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div[2]/div[2]/div/div/div[2]/div[4]/div/a/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/original/payment-asset/2020/10/20/44f4468f-77b2-47eb-9124-aac203d23b60-1603172663513-a9e4a0f20cc798bfd435450a26375714.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tix-ui-fadeIn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;content layout&quot;]/div[@class=&quot;main-wrap&quot;]/div[@class=&quot;landing-page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;payment-list&quot;]/div[2]/div[@class=&quot;payment-methods-list&quot;]/div[@class=&quot;card payment-group white&quot;]/a[1]/div[@class=&quot;payment-method-item&quot;]/div[@class=&quot;method-type-name&quot;]/div[@class=&quot;method-type-logo&quot;]/div[@class=&quot;logo-item&quot;]/img[@class=&quot;tix-ui-fadeIn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div[2]/div/div/div[2]/div[4]/div/a/div/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/original/payment-asset/2020/10/20/44f4468f-77b2-47eb-9124-aac203d23b60-1603172663513-a9e4a0f20cc798bfd435450a26375714.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/div/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
