<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Indonesia</name>
   <tag></tag>
   <elementGuidId>cf825412-0214-4ae2-8749-1cb25fbed31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div[3]/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[3]/div/div/div/div[3]/div[2]/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.list-data.read-it</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-data read-it</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;left-side&quot;]/div[3]/div[@class=&quot;booking&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container content&quot;]/div[@class=&quot;pull-left main&quot;]/div[@class=&quot;form&quot;]/div[@class=&quot;wrapper-passenger-details&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;person-with-passport-panel&quot;]/div[@class=&quot;body-passenger-details&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-6&quot;]/div[@class=&quot;tix-core-country-dropdown country-has-error&quot;]/div[@class=&quot;flight-dropdown-searchbox  error&quot;]/div[@class=&quot;box-with-search fadeInDown-enter-done&quot;]/div[@class=&quot;list-menu list-menu-flight-dropdown-searchbox&quot;]/ul[@class=&quot;ul-list-menu&quot;]/li[@class=&quot;list-data read-it&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[3]/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[3]/div/div/div/div[3]/div[2]/ul/li</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kewarganegaraan harus diisi'])[1]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kewarganegaraan'])[1]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aruba'])[1]/preceding::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/ul/li</value>
   </webElementXpaths>
</WebElementEntity>
